import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import QueryProvider from '@/components/QueryProvider';
import '@/globals.css';
import Theme from '@/components/Theme';
import Title from '@/components/Title';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Pokémon',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
	modal,
}: Readonly<{
	children: React.ReactNode;
	modal: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased text-background bg-foreground dark:text-foreground dark:bg-background`}>
				<QueryProvider>
					<header className="relative">
						<Title>Pokémon</Title>
						<div className="hidden md:block absolute top-0 right-0 px-4">
							<Theme />
						</div>
					</header>
					{children}
					{modal}
				</QueryProvider>
			</body>
		</html>
	);
}
